package dev.envoix.app.ui

import android.content.Context
import android.net.Uri
import android.provider.OpenableColumns
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material3.Icon
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import dev.envoix.app.InviteCodec
import dev.envoix.app.SettingsStore

/**
 * New-transfer sheet. The top is a mutually-exclusive **Show QR / Scan QR** pane
 * (your own code vs a live inline scanner); below it a code field to type/paste a
 * code, then the role picker, the file/save path, and the start button. Scanning
 * fills the code and picks the opposite role, so both sides never share a role.
 */
@Composable
fun NewTransferSheet(
    onReceive: (code: String, broker: String, relay: String, qrPayload: String?) -> Unit,
    onSend: (code: String, broker: String, relay: String, file: Uri, qrPayload: String?) -> Unit,
) {
    val colors = Envoix.colors
    val context = LocalContext.current
    val settings by SettingsStore.settings.collectAsState()
    val broker = settings.broker
    val relay = settings.relay

    var role by remember { mutableStateOf(settings.defaultRole) }
    var typed by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<Pair<String, String>?>(null) } // code, qr payload
    var scannedBroker by remember { mutableStateOf<String?>(null) }
    var scannedRelay by remember { mutableStateOf<String?>(null) }
    var fileUri by remember { mutableStateOf<Uri?>(null) }
    var fileName by remember { mutableStateOf<String?>(null) }
    var topMode by remember { mutableStateOf("show") } // "show" | "scan"

    val filePicker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
        if (uri != null) {
            fileUri = uri
            fileName = displayName(context, uri)
        }
    }
    val folderPicker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocumentTree()) { uri ->
        if (uri != null) SettingsStore.setSaveTree(context, uri)
    }
    val joining = typed.isNotBlank()

    // (Re)generate our own code whenever the role changes and we're not joining.
    LaunchedEffect(role, joining) {
        if (!joining) generated = InviteCodec.generate(role, broker, relay)
    }

    fun applyScanned(scanned: String) {
        val inv = InviteCodec.parse(scanned) ?: return
        typed = inv.code
        scannedBroker = inv.broker
        scannedRelay = inv.relay
        InviteCodec.oppositeRole(inv.role)?.let { role = it }
        topMode = "show" // stop the camera; the code is filled in now
    }

    val code = if (joining) typed.trim() else generated?.first
    val useBroker = scannedBroker ?: broker
    val useRelay = scannedRelay ?: relay
    val ready = !code.isNullOrBlank() && code.contains("-") && (role == "receive" || fileUri != null)

    Column(
        Modifier.fillMaxWidth().verticalScroll(rememberScrollState())
            .padding(horizontal = 20.dp).padding(bottom = 28.dp),
    ) {
        Text("New transfer", color = colors.text, fontSize = 21.sp, fontWeight = FontWeight.ExtraBold)
        Spacer(Modifier.height(14.dp))

        // ---- top pane: show my QR vs scan one ----
        Row(
            Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp))
                .background(colors.bg).border(1.dp, colors.line, RoundedCornerShape(12.dp)).padding(3.dp),
        ) {
            SegTab("Show QR", topMode == "show", Modifier.weight(1f)) { topMode = "show" }
            SegTab("Scan QR", topMode == "scan", Modifier.weight(1f)) { topMode = "scan" }
        }

        Spacer(Modifier.height(14.dp))
        Box(Modifier.fillMaxWidth().heightIn(min = 250.dp), contentAlignment = Alignment.Center) {
            if (topMode == "scan") {
                InlineScanner(onScanned = ::applyScanned, modifier = Modifier.fillMaxWidth())
            } else if (joining) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Text("You'll join", color = colors.muted, fontSize = 13.sp)
                    Spacer(Modifier.height(6.dp))
                    Text(typed, color = colors.accent, fontSize = 18.sp, fontWeight = FontWeight.Bold, fontFamily = FontFamily.Monospace)
                    Spacer(Modifier.height(6.dp))
                    Text("clear the code below to show your own", color = colors.muted, fontSize = 11.sp)
                }
            } else if (generated != null) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    QrCode(generated!!.second, side = 168.dp)
                    Spacer(Modifier.height(12.dp))
                    val clip = LocalClipboardManager.current
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(
                            generated!!.first,
                            color = colors.text, fontSize = 15.sp, fontWeight = FontWeight.SemiBold,
                            fontFamily = FontFamily.Monospace,
                        )
                        Spacer(Modifier.width(8.dp))
                        Icon(
                            Icons.Default.ContentCopy, "Copy code",
                            tint = colors.muted,
                            modifier = Modifier.size(18.dp).clip(CircleShape)
                                .clickable { clip.setText(AnnotatedString(generated!!.first)) },
                        )
                    }
                }
            }
        }

        // ---- code field (type/paste a code to join) ----
        Spacer(Modifier.height(16.dp))
        OutlinedTextField(
            value = typed,
            onValueChange = { typed = it.trim(); scannedBroker = null; scannedRelay = null },
            placeholder = { Text("or enter a code to join…") },
            singleLine = true,
            modifier = Modifier.fillMaxWidth(),
        )

        // ---- role picker ----
        Spacer(Modifier.height(16.dp))
        Text("I WANT TO", color = colors.muted, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.sp)
        Spacer(Modifier.height(6.dp))
        Row(
            Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp))
                .background(colors.bg).border(1.dp, colors.line, RoundedCornerShape(12.dp)).padding(3.dp),
        ) {
            SegTab("Send", role == "send", Modifier.weight(1f)) { role = "send" }
            SegTab("Receive", role == "receive", Modifier.weight(1f)) { role = "receive" }
        }

        // ---- path: file to send (required) or where received files land ----
        Spacer(Modifier.height(14.dp))
        if (role == "send") {
            PathRow("FILE TO SEND", fileName ?: "Choose a file…", placeholder = fileName == null) {
                filePicker.launch(arrayOf("*/*"))
            }
        } else {
            PathRow("SAVE TO", SettingsStore.saveLabel(context), placeholder = false) {
                folderPicker.launch(null)
            }
        }

        // ---- start ----
        Spacer(Modifier.height(16.dp))
        Box(
            Modifier.fillMaxWidth().height(52.dp).clip(RoundedCornerShape(14.dp))
                .background(colors.accent.copy(alpha = if (ready) 1f else 0.4f))
                .clickable(enabled = ready) {
                    val c = code ?: return@clickable
                    val qr = if (joining) null else generated?.second
                    if (role == "send") onSend(c, useBroker, useRelay, fileUri!!, qr) else onReceive(c, useBroker, useRelay, qr)
                },
            contentAlignment = Alignment.Center,
        ) {
            Text(
                if (role == "send") "Send" else "Receive",
                color = Color.White, fontWeight = FontWeight.Bold, fontSize = 16.sp,
            )
        }
    }
}

@Composable
private fun SegTab(text: String, selected: Boolean, modifier: Modifier, onClick: () -> Unit) {
    val colors = Envoix.colors
    Box(
        modifier.clip(RoundedCornerShape(9.dp))
            .background(if (selected) colors.accent else Color.Transparent)
            .clickable(onClick = onClick).padding(vertical = 9.dp),
        contentAlignment = Alignment.Center,
    ) {
        Text(
            text,
            color = if (selected) Color.White else colors.muted,
            fontWeight = FontWeight.Bold, fontSize = 14.sp,
        )
    }
}

/** A labelled path row: a tappable file/folder picker (onClick != null) or a
 *  read-only value. */
@Composable
private fun PathRow(label: String, value: String, placeholder: Boolean, onClick: (() -> Unit)?) {
    val colors = Envoix.colors
    Text(label, color = colors.muted, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.sp)
    Spacer(Modifier.height(6.dp))
    Row(
        Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp))
            .border(1.dp, colors.line, RoundedCornerShape(12.dp))
            .then(if (onClick != null) Modifier.clickable(onClick = onClick) else Modifier)
            .padding(horizontal = 14.dp, vertical = 14.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        Text(
            value,
            color = if (placeholder) colors.muted else colors.text,
            fontSize = 14.sp, fontFamily = FontFamily.Monospace,
            maxLines = 1, overflow = TextOverflow.Ellipsis,
            modifier = Modifier.weight(1f, fill = false),
        )
        if (onClick != null) {
            Icon(Icons.Default.ChevronRight, null, tint = colors.muted, modifier = Modifier.size(20.dp))
        }
    }
}

private fun displayName(context: Context, uri: Uri): String =
    context.contentResolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)
        ?.use { c -> if (c.moveToFirst()) c.getString(0) else null } ?: "file"
