package dev.envoix.app.ui

import android.content.Context
import android.net.Uri
import android.provider.OpenableColumns
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.QrCodeScanner
import androidx.compose.material3.Icon
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import dev.envoix.app.InviteCodec
import dev.envoix.app.SettingsStore

/**
 * New-transfer sheet: enter/scan a code to join, or show your own generated QR +
 * code and pick a role. Scanning auto-selects the opposite role (from the
 * invite's role hint), so both sides never end up on the same role.
 */
@Composable
fun NewTransferSheet(
    onReceive: (code: String, broker: String, relay: String, qrPayload: String?) -> Unit,
    onSend: (code: String, broker: String, relay: String, file: Uri, qrPayload: String?) -> Unit,
) {
    val colors = Envoix.colors
    val context = LocalContext.current
    val settings by SettingsStore.settings.collectAsState()
    val broker = settings.broker
    val relay = settings.relay

    var role by remember { mutableStateOf(settings.defaultRole) }
    var typed by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<Pair<String, String>?>(null) } // code, qr payload
    var scannedBroker by remember { mutableStateOf<String?>(null) }
    var scannedRelay by remember { mutableStateOf<String?>(null) }
    var fileUri by remember { mutableStateOf<Uri?>(null) }
    var fileName by remember { mutableStateOf<String?>(null) }
    val filePicker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
        if (uri != null) {
            fileUri = uri
            fileName = displayName(context, uri)
        }
    }
    val joining = typed.isNotBlank()

    // (Re)generate our own code whenever the role changes and we're not joining.
    LaunchedEffect(role, joining) {
        if (!joining) generated = InviteCodec.generate(role, broker, relay)
    }

    val scanner = rememberLauncherForActivityResult(ScanContract()) { result ->
        val scanned = result.contents ?: return@rememberLauncherForActivityResult
        val inv = InviteCodec.parse(scanned) ?: return@rememberLauncherForActivityResult
        typed = inv.code
        scannedBroker = inv.broker
        scannedRelay = inv.relay
        InviteCodec.oppositeRole(inv.role)?.let { role = it }
    }

    val code = if (joining) typed.trim() else generated?.first
    val useBroker = scannedBroker ?: broker
    val useRelay = scannedRelay ?: relay
    val ready = !code.isNullOrBlank() && code.contains("-") && (role == "receive" || fileUri != null)

    Column(
        Modifier.fillMaxWidth().verticalScroll(rememberScrollState())
            .padding(horizontal = 20.dp).padding(bottom = 28.dp),
    ) {
        Text("New transfer", color = colors.text, fontSize = 21.sp, fontWeight = FontWeight.ExtraBold)
        Spacer(Modifier.height(14.dp))

        // ---- join: enter a code + scan ----
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(9.dp)) {
            OutlinedTextField(
                value = typed,
                onValueChange = { typed = it.trim(); scannedBroker = null; scannedRelay = null },
                placeholder = { Text("enter a code to join…") },
                singleLine = true,
                modifier = Modifier.weight(1f),
            )
            Box(
                Modifier.size(52.dp).clip(RoundedCornerShape(12.dp))
                    .border(1.dp, colors.line, RoundedCornerShape(12.dp))
                    .clickable {
                        scanner.launch(
                            ScanOptions()
                                .setDesiredBarcodeFormats(ScanOptions.QR_CODE)
                                .setBeepEnabled(false)
                                .setOrientationLocked(false)
                                .setPrompt("Scan an Envoix code"),
                        )
                    },
                contentAlignment = Alignment.Center,
            ) {
                Icon(Icons.Default.QrCodeScanner, "Scan a QR code", tint = colors.accent, modifier = Modifier.size(24.dp))
            }
        }

        // ---- initiate: show your own QR (only when not joining) ----
        if (!joining && generated != null) {
            Spacer(Modifier.height(14.dp))
            Divider("or show your code")
            Spacer(Modifier.height(12.dp))
            Box(Modifier.fillMaxWidth(), contentAlignment = Alignment.Center) {
                QrCode(generated!!.second, side = 150.dp)
            }
            Spacer(Modifier.height(10.dp))
            val clip = LocalClipboardManager.current
            Row(
                Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.Center,
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text(
                    generated!!.first,
                    color = colors.text, fontSize = 15.sp, fontWeight = FontWeight.SemiBold,
                    fontFamily = FontFamily.Monospace,
                )
                Spacer(Modifier.width(8.dp))
                Icon(
                    Icons.Default.ContentCopy, "Copy code",
                    tint = colors.muted,
                    modifier = Modifier.size(18.dp).clip(CircleShape)
                        .clickable { clip.setText(AnnotatedString(generated!!.first)) },
                )
            }
        }

        Spacer(Modifier.height(16.dp))
        // ---- role picker (sets your role + the QR's role hint) ----
        Text(
            "I WANT TO",
            color = colors.muted, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.sp,
        )
        Spacer(Modifier.height(6.dp))
        Row(
            Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp))
                .background(colors.bg).border(1.dp, colors.line, RoundedCornerShape(12.dp)).padding(3.dp),
        ) {
            RoleTab("Send", role == "send", Modifier.weight(1f)) { role = "send" }
            RoleTab("Receive", role == "receive", Modifier.weight(1f)) { role = "receive" }
        }

        // ---- path: the file to send (required), or where received files land ----
        Spacer(Modifier.height(14.dp))
        if (role == "send") {
            PathRow("FILE TO SEND", fileName ?: "Choose a file…", placeholder = fileName == null) {
                filePicker.launch(arrayOf("*/*"))
            }
        } else {
            PathRow("SAVE TO", "Downloads / ${settings.saveFolder}", placeholder = false, onClick = null)
        }

        Spacer(Modifier.height(16.dp))
        // ---- start ----
        Box(
            Modifier.fillMaxWidth().height(52.dp).clip(RoundedCornerShape(14.dp))
                .background(colors.accent.copy(alpha = if (ready) 1f else 0.4f))
                .clickable(enabled = ready) {
                    val c = code ?: return@clickable
                    // Advertise our QR only when we initiated (not when joining a code).
                    val qr = if (joining) null else generated?.second
                    if (role == "send") onSend(c, useBroker, useRelay, fileUri!!, qr) else onReceive(c, useBroker, useRelay, qr)
                },
            contentAlignment = Alignment.Center,
        ) {
            Text(
                if (role == "send") "Send" else "Receive",
                color = Color.White, fontWeight = FontWeight.Bold, fontSize = 16.sp,
            )
        }
    }
}

@Composable
private fun RoleTab(text: String, selected: Boolean, modifier: Modifier, onClick: () -> Unit) {
    val colors = Envoix.colors
    Box(
        modifier.clip(RoundedCornerShape(9.dp))
            .background(if (selected) colors.accent else Color.Transparent)
            .clickable(onClick = onClick).padding(vertical = 9.dp),
        contentAlignment = Alignment.Center,
    ) {
        Text(
            text,
            color = if (selected) Color.White else colors.muted,
            fontWeight = FontWeight.Bold, fontSize = 14.sp,
        )
    }
}

@Composable
private fun Divider(label: String) {
    val colors = Envoix.colors
    Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(12.dp)) {
        Box(Modifier.weight(1f).height(1.dp).background(colors.line))
        Text(label, color = colors.muted, fontSize = 12.sp)
        Box(Modifier.weight(1f).height(1.dp).background(colors.line))
    }
}

/** A labelled path row: a tappable file/folder picker (onClick != null) or a
 *  read-only value. */
@Composable
private fun PathRow(label: String, value: String, placeholder: Boolean, onClick: (() -> Unit)?) {
    val colors = Envoix.colors
    Text(label, color = colors.muted, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.sp)
    Spacer(Modifier.height(6.dp))
    Row(
        Modifier.fillMaxWidth().clip(RoundedCornerShape(12.dp))
            .border(1.dp, colors.line, RoundedCornerShape(12.dp))
            .then(if (onClick != null) Modifier.clickable(onClick = onClick) else Modifier)
            .padding(horizontal = 14.dp, vertical = 14.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        Text(
            value,
            color = if (placeholder) colors.muted else colors.text,
            fontSize = 14.sp, fontFamily = FontFamily.Monospace,
            maxLines = 1, overflow = TextOverflow.Ellipsis,
            modifier = Modifier.weight(1f, fill = false),
        )
        if (onClick != null) {
            Icon(Icons.Default.ChevronRight, null, tint = colors.muted, modifier = Modifier.size(20.dp))
        }
    }
}

private fun displayName(context: Context, uri: Uri): String =
    context.contentResolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)
        ?.use { c -> if (c.moveToFirst()) c.getString(0) else null } ?: "file"
