[package]
name = "envoix-android-jni"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "envoix_jni"

[dependencies]
envoix-client = { path = "../../crates/envoix-client" }
base64.workspace = true
jni = "0.21"
ndk-context = "0.1"
tokio = { version = "1", features = ["rt-multi-thread"] }
serde.workspace = true
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
