//! Resolves THIS build's deployment identity out of `deploy/environments.toml`.
//!
//! The identity is not a constant anybody types and not a second copy of the
//! catalogue: `src/catalogue.rs` is included here verbatim, so the parser, the
//! deployability rule and the endpoint derivations are literally the same code
//! the library and `xtask deploy-check` run. An environment the catalogue will
//! not deploy therefore cannot be built for — the panic below is a compile
//! error, not a lint somebody can suppress.
#![allow(dead_code)]

use std::env;
use std::fs;
use std::path::PathBuf;

include!("src/catalogue.rs");

/// Relative to this crate root, the same file `CATALOGUE_TOML` includes.
const CATALOGUE: &str = "../../../deploy/environments.toml";
/// Which environment to build for. Unset means the catalogue's own
/// `default_build_environment`, so an ordinary `cargo build` is a decision the
/// catalogue made rather than one this script invented.
const ENVIRONMENT_VAR: &str = "ENVOIX_ENVIRONMENT";

fn main() {
    println!("cargo:rerun-if-changed={CATALOGUE}");
    println!("cargo:rerun-if-changed=src/catalogue.rs");
    println!("cargo:rerun-if-env-changed={ENVIRONMENT_VAR}");

    let text = fs::read_to_string(CATALOGUE)
        .unwrap_or_else(|error| panic!("reading {CATALOGUE}: {error}"));
    let catalogue =
        DeploymentCatalogue::parse(&text).unwrap_or_else(|error| panic!("{CATALOGUE}: {error}"));
    let name = env::var(ENVIRONMENT_VAR)
        .unwrap_or_else(|_| catalogue.validation.default_build_environment.clone());
    let identity = catalogue.identity(&name).unwrap_or_else(|error| {
        panic!("{ENVIRONMENT_VAR}={name}: {error}");
    });

    let out =
        PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets OUT_DIR")).join("build_target.rs");
    let source = format!(
        "// @generated by build.rs from {CATALOGUE}. Do not edit.\n{}",
        identity.render_static("BUILD_TARGET")
    );
    fs::write(&out, source).unwrap_or_else(|error| panic!("writing {}: {error}", out.display()));
}
