FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge

RUN apt-get update && \
    apt-get install -y gcc-10 g++-10 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100 && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-10 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 100
