#!/usr/bin/env bash
# flutter_creates_a_transfer_without_the_debug_bridge — F2b instrumentation.
# RUN BY THE RECONCILER ONLY (one emulator; legs never touch adb).
#
# This one deliberately does NOT chain from `f1b`/`f1c`/`f2a`. Those install the
# dev-DEBUG APK and seed a card through `E2eBridge`, and both would defeat the
# claim being made here: F2b's headline is that a card comes into existence from
# the real UI in a build where the debug creation bridge is not present at all.
# So it installs the dev-RELEASE APK over a clean uninstall — no `E2eBridge`
# class, no instrumentation JNI symbols, no exported service, and no cards.
#
# What it proves, in order:
#
#   1. the app starts with NO cards, and the intent that creates one in a debug
#      build does nothing here — the bridge is not merely unused, it is gone;
#   2. a MALFORMED invite is refused BY THE AUTHORITY, in the authority's own
#      typed words, drawn on screen, with no card created — the app never
#      decided the text was bad, because it has no invite grammar to decide with;
#   3. a VALID invite — generated by the core, not by this script — creates a
#      card from the sheet, and that card then renders in the home list carrying
#      the room code that was inside the pasted invite's payload;
#   4. the send path reaches the system document picker, and cancelling it
#      creates nothing.
#
# What it does NOT prove, stated plainly rather than implied:
#
#   * the SEND path past the picker. SAF's picker is system UI whose layout,
#     package and contents differ across API levels and images; driving it would
#     be a fragile green line, and faking the pick — or routing around SAF —
#     would assert something the product does not do. So this stops at "the
#     picker opened". A granted pick, and therefore the `SourceHandle` duty
#     being dispatched, executed and admitted against a REAL content URI, is not
#     covered on a device by anything in this repository. Headlessly it is:
#     `flutter_creates_a_transfer_without_the_debug_bridge` (Rust) drives the
#     whole duty round trip, and `platform_duty_crash_matrix` models the pick
#     lane's crash windows.
#   * that the send button is disabled before a pick. That is `flutter test`'s
#     (`the send button waits for the platform, not for a rule`); re-proving it
#     here would need instrumentation for a widget's enabled state.
#   * anything about a peer. Nothing connects in F2b; a joined card rests in
#     `Connecting` because the executor has no prepared launch (BN4's named
#     deferral). This asserts the card exists and renders, not that it transfers.
#
# Every coordinate is read from the line the CONTROL printed as it laid itself
# out, captured once while the sheet is open. `Join` sits one row below
# `Start sending`; a guessed tap is not a benign miss here.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../../../.." && pwd)"
ADB="${ADB:-adb}"
APP_ID="${APP_ID:-app.envoix.host.dev}"
ACTIVITY="$APP_ID/app.envoix.host.MainActivity"
SVC="$APP_ID/app.envoix.host.EnvoixHostService"
APK="${APK:-$HERE/../app/build/outputs/apk/dev/release/app-dev-release.apk}"

# Text the invite grammar recognises as Envoix and then refuses: valid base64url
# that is not a payload. Deliberately made only of characters `input text`
# cannot mangle, so a refusal is the AUTHORITY's answer and not a transcription
# accident. Which refusal it earns is pinned on the Rust side by
# `every_invite_verdict_crosses_as_its_own_refusal`, so this expects that exact
# one — unless the caller supplied their own text, in which case any refusal
# from the authority is the claim.
DEFAULT_MALFORMED="envoix:zzzz"
MALFORMED="${MALFORMED:-$DEFAULT_MALFORMED}"
EXPECTED_REFUSAL="refused:inviteMalformed"

# logcat is never cleared after the app starts: the instrumentation ledger
# prints each distinct line once, so a clear would erase coordinates that will
# not be printed again. Answers are told apart by taking the most recent.
flutter_log() { "$ADB" logcat -d -s flutter; }

control() {
    flutter_log |
        sed -n "s/.*envoix-f2b sheet control=$1 x=\(-\{0,1\}[0-9]\{1,\}\) y=\(-\{0,1\}[0-9]\{1,\}\).*/\1 \2/p" |
        tail -1
}
# A control the app placed OFF the screen is not one this can tap — and that
# is a different failure from an app that printed nothing at all. Saying
# which is the difference between "look at the widget" and "look at debugPrint".
control_line() {
    flutter_log | sed -n "s/.*\(envoix-f2b sheet control=$1 .*\)/\1/p" | tail -1
}
require_control() {
    local point
    point="$(control "$1")"
    [ -n "$point" ] || {
        echo "FAIL: the app never reported where it drew the '$1' control"
        flutter_log | tail -30
        exit 1
    }
    printf '%s\n' "$point"
}
tap_at() { "$ADB" shell input tap $1; }

# `input text` drops characters on a long string — an invite is ~190 of them,
# and a partial one is a DIFFERENT test: the authority refuses it as damaged,
# which is correct behaviour and not what this step is asking about. Type it in
# chunks so the field ends up holding the invite the core actually produced.
# The sheet moves while the keyboard is up, and it moves again when an answer
# appears beneath it. Reading a control's position and then tapping it is a race
# against that movement. Put the keyboard away first: the layout stops, the app
# re-reports every control where it has come to rest, and the tap has a
# stationary target.
settle_layout() {
    "$ADB" shell input keyevent 4
    sleep 2.5
}

type_text() {
    local text="$1" i=0 n=${#1}
    while [ "$i" -lt "$n" ]; do
        "$ADB" shell input text "$(printf '%s' "${text:$i:32}")"
        i=$((i + 32))
        sleep 0.35
    done
}
# Tapping a control by coordinate races the layout: the sheet moves when the
# keyboard opens, when the field grows to fit wrapped text, and again when an
# answer appears beneath it. Rather than trying to freeze the layout, tap and
# then CHECK — re-reading the control's latest reported position each time, so
# every attempt aims at where the app most recently said the button is.
join_until_answered() {
    local before="$1" attempt=0 now
    while [ "$attempt" -lt 5 ]; do
        tap_at "$(require_control join)"
        sleep 5
        now="$(create_answer)"
        if [ "$now" != "$before" ]; then
            printf '%s' "$now"
            return 0
        fi
        attempt=$((attempt + 1))
    done
    return 1
}

create_answer() {
    flutter_log |
        sed -n 's/.*envoix-f2b create id=[0-9a-f]\{32\} kind=[a-z]\{1,\} answer=\([^ ]*\).*/\1/p' |
        tail -1
}
rendered_cards() {
    flutter_log | sed -n 's/.*envoix-f1b rendered card=\([0-9a-f]\{16\}\).*/\1/p' | sort -u | tr '\n' ' '
}

# ---- the invite, generated by the core -----------------------------------
# Not written out here: a script that invented an invite would be asserting
# against its own idea of the grammar. The headless invariant test publishes a
# real one through the real projection, so run it and read what it wrote.
INVITE="${INVITE:-}"
EXPECTED_CODE="${INVITE_CODE:-}"
if [ -z "$INVITE" ]; then
    echo "==> ask the core for an invite"
    (cd "$REPO" && cargo test -q -p envoix-host-android --test frontend_lane \
        flutter_creates_a_transfer_without_the_debug_bridge >/dev/null)
    FIXTURES="$REPO/target/tmp/create-lane"
    [ -f "$FIXTURES/invite.txt" ] && [ -f "$FIXTURES/code.txt" ] || {
        echo "FAIL: the headless test wrote no invite in $FIXTURES"
        exit 1
    }
    INVITE=$(cat "$FIXTURES/invite.txt")
    EXPECTED_CODE=$(cat "$FIXTURES/code.txt")
fi
case "$INVITE" in
envoix://*) ;;
*)
    echo "FAIL: '$INVITE' is not an invite the core produced"
    exit 1
    ;;
esac
echo "    invite: $INVITE"
echo "    the room code inside it: ${EXPECTED_CODE:-<not supplied>}"

# ---- 1. a clean release install, with no cards and no bridge -------------
"$ADB" wait-for-device
echo "==> install the RELEASE apk over a clean slate"
[ -f "$APK" ] || {
    echo "FAIL: $APK is missing; run ./gradlew :app:assembleRelease"
    exit 1
}
"$ADB" uninstall "$APP_ID" >/dev/null 2>&1 || true
"$ADB" install -r "$APK"

"$ADB" logcat -c
"$ADB" shell am start -n "$ACTIVITY" >/dev/null
sleep 6

if [ -z "$(control new-transfer)" ] && [ -n "$(control_line new-transfer)" ]; then
    echo "FAIL: the app located its new-transfer control off the screen:"
    echo "      $(control_line new-transfer)"
    echo "      That is a widget-placement bug, not a logging one — the line"
    echo "      arrived, its coordinates are just not tappable."
    exit 1
fi

if [ -z "$(control new-transfer)" ]; then
    echo "FAIL: the release build printed no instrumentation at all."
    echo "      Either the app did not start, or this Flutter release build"
    echo "      drops \`debugPrint\`. Re-running with"
    echo "      APK=$HERE/../app/build/outputs/apk/dev/debug/app-dev-debug.apk"
    echo "      still proves creation-from-the-UI, but NOT that the debug bridge"
    echo "      is absent — say which you ran."
    flutter_log | tail -30
    exit 1
fi
[ -z "$(rendered_cards)" ] || {
    echo "FAIL: a freshly installed app already has cards: $(rendered_cards)"
    exit 1
}
NEW_TRANSFER="$(require_control new-transfer)"
echo "    the app is up with no cards"

echo "==> the debug creation bridge is not there to be used"
"$ADB" shell am start-foreground-service -n "$SVC" \
    -a "$APP_ID.action.e2e-create" --es name f2b.bin --el total 4096 \
    >/dev/null 2>&1 || true
sleep 3
if "$ADB" logcat -d -s EnvoixE2e | grep -q .; then
    echo "FAIL: the release build answered the debug creation intent"
    "$ADB" logcat -d -s EnvoixE2e | tail -10
    exit 1
fi
[ -z "$(rendered_cards)" ] || {
    echo "FAIL: the debug intent created a card in a release build: $(rendered_cards)"
    exit 1
}
echo "    the e2e-create intent did nothing, and no card exists"

# ---- 2. a malformed invite: the authority refuses, nothing is created ----
echo "==> open the new-transfer sheet"
tap_at "$NEW_TRANSFER"
sleep 3
# Assert the sheet drew these; do NOT reuse the values as tap targets. Opening
# the keyboard slides the sheet up, the app re-reports every control at its new
# place, and a coordinate captured here would land under the keyboard. Each tap
# re-reads instead.
require_control invite >/dev/null
require_control join >/dev/null
require_control choose >/dev/null

echo "==> a malformed invite"
tap_at "$(require_control invite)"
sleep 1
type_text "$MALFORMED"
settle_layout
REFUSED=$(join_until_answered "")
[ -n "$REFUSED" ] || {
    echo "FAIL: joining a malformed invite drew no answer on screen at all"
    flutter_log | tail -30
    exit 1
}
case "$REFUSED" in
refused:*) ;;
*)
    echo "FAIL: a malformed invite must be REFUSED by the authority, got '$REFUSED'"
    exit 1
    ;;
esac
if [ "$MALFORMED" = "$DEFAULT_MALFORMED" ] && [ "$REFUSED" != "$EXPECTED_REFUSAL" ]; then
    echo "FAIL: '$MALFORMED' earns $EXPECTED_REFUSAL from the grammar, but the"
    echo "      app drew '$REFUSED' — the text may not have reached the field"
    exit 1
fi
echo "    the authority refused it: $REFUSED"
[ -z "$(rendered_cards)" ] || {
    echo "FAIL: a refused invite created a card: $(rendered_cards)"
    exit 1
}

# Dismissing the sheet drops its controller, so reopening gives an empty field —
# clearing text with keyevents is the fragile way to do the same thing.
"$ADB" shell input keyevent KEYCODE_BACK
sleep 2

# ---- 3. a real invite: a card comes into existence ----------------------
echo "==> a real invite"
tap_at "$NEW_TRANSFER"
sleep 3
tap_at "$(require_control invite)"
sleep 1
type_text "$INVITE"
settle_layout
ANSWER=$(join_until_answered "$REFUSED")
[ "$ANSWER" != "$REFUSED" ] && [ -n "$ANSWER" ] || {
    echo "FAIL: the second join drew no new answer; the tap may have missed"
    flutter_log | tail -30
    exit 1
}
CARD=$(printf '%s\n' "$ANSWER" | sed -n 's/^created:\([0-9a-f]\{16\}\)$/\1/p')
[ -n "$CARD" ] || {
    echo "FAIL: the authority did not create a card, it answered '$ANSWER'"
    echo "      (a mangled paste is refused here; check the invite reached the field)"
    flutter_log | tail -30
    exit 1
}
echo "    the authority created card $CARD"

echo "==> the card renders in the home list"
"$ADB" shell input keyevent KEYCODE_BACK
sleep 4
flutter_log | grep -q "envoix-f1b rendered card=$CARD" || {
    echo "FAIL: card $CARD was created but the home list never drew it"
    flutter_log | tail -30
    exit 1
}
CARD_LINE=$(flutter_log | sed -n "s/.*\(envoix-f2a card=$CARD .*\)/\1/p" | tail -1)
[ -n "$CARD_LINE" ] || {
    echo "FAIL: card $CARD drew no state line"
    exit 1
}
STATE=$(printf '%s\n' "$CARD_LINE" | sed -n 's/.*state=\(.*\)$/\1/p')
INVITE_LINE=$(flutter_log | sed -n "s/.*\(envoix-f2b invite card=$CARD .*\)/\1/p" | tail -1)
[ -n "$INVITE_LINE" ] || {
    echo "FAIL: the joined card drew no invite; a card must show the channel it joined"
    exit 1
}
CODE=$(printf '%s\n' "$INVITE_LINE" | sed -n 's/.*code=\([^ ]*\).*/\1/p')
if [ -n "$EXPECTED_CODE" ] && [ "$CODE" != "$EXPECTED_CODE" ]; then
    echo "FAIL: the card shows room code '$CODE', but the invite carried '$EXPECTED_CODE'"
    exit 1
fi
echo "    card $CARD is '$STATE' on room code $CODE"

# ---- 4. the send path reaches the picker, and cancelling creates nothing --
echo "==> the send path reaches the system document picker"
BEFORE_SEND=$(rendered_cards)
tap_at "$NEW_TRANSFER"
sleep 3
tap_at "$(require_control choose)"
sleep 5
if "$ADB" shell dumpsys activity activities | grep -qi documentsui; then
    echo "    the system document picker is on screen"
else
    echo "FAIL: tapping 'Choose a file' did not reach a document picker"
    "$ADB" shell dumpsys activity activities |
        grep -i "topResumedActivity\|mResumedActivity" | head -3
    exit 1
fi
"$ADB" shell input keyevent KEYCODE_BACK
sleep 3
"$ADB" shell input keyevent KEYCODE_BACK
sleep 3
AFTER_SEND=$(rendered_cards)
[ "$BEFORE_SEND" = "$AFTER_SEND" ] || {
    echo "FAIL: cancelling the picker changed the cards ($BEFORE_SEND -> $AFTER_SEND)"
    exit 1
}
LAST=$(create_answer)
[ "$LAST" = "$ANSWER" ] || {
    echo "FAIL: a cancelled pick produced a create answer: $LAST"
    exit 1
}
echo "    a cancelled pick created nothing"

echo "PASS: flutter_creates_a_transfer_without_the_debug_bridge"
echo "      a RELEASE build with no E2eBridge refused '$MALFORMED' as $REFUSED,"
echo "      created card $CARD from a core-generated invite typed into the sheet,"
echo "      drew it as '$STATE' on room code $CODE, and reached the system picker"
echo "      without creating anything when the pick was cancelled."
echo "      NOT covered: the send path past the picker (see this file's header)."
